package TaxCalculator;


/**
* TaxCalculator/Tax.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaxCalculator.idl
* Thursday, March 13, 2014 10:59:55 AM EDT
*/

public interface Tax extends TaxOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tax
