package TaxCalculator;


/**
* TaxCalculator/Tax.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaxCalculator.idl
* Wednesday, March 19, 2014 8:55:44 PM EDT
*/

public interface Tax extends TaxOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tax
