package TaxCalculator;


/**
* TaxCalculator/TaxOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaxCalculator.idl
* Wednesday, March 19, 2014 8:55:44 PM EDT
*/

public interface TaxOperations 
{
  double getTax (double cost);
  void shutdown ();
} // interface TaxOperations
