package Inter;

/**
* Inter/DBClientListenerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Rinard.idl
* Thursday, March 6, 2014 10:30:47 AM EST
*/

public final class DBClientListenerHolder implements org.omg.CORBA.portable.Streamable
{
  public Inter.DBClientListener value = null;

  public DBClientListenerHolder ()
  {
  }

  public DBClientListenerHolder (Inter.DBClientListener initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Inter.DBClientListenerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Inter.DBClientListenerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Inter.DBClientListenerHelper.type ();
  }

}
