package Inter;


/**
* Inter/DBControlServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Rinard.idl
* Thursday, March 6, 2014 10:30:47 AM EST
*/

public interface DBControlServer extends DBControlServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DBControlServer
