package Inter;


/**
* Inter/DBControlServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Rinard.idl
* Thursday, March 6, 2014 10:30:47 AM EST
*/

public interface DBControlServerOperations 
{
  void requestConnect (Inter.DBClientListener dbc);
} // interface DBControlServerOperations
