package TaxCalculator;

/**
* TaxCalculator/TaxHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaxCalculator.idl
* Tuesday, March 25, 2014 8:47:52 AM EDT
*/

public final class TaxHolder implements org.omg.CORBA.portable.Streamable
{
  public TaxCalculator.Tax value = null;

  public TaxHolder ()
  {
  }

  public TaxHolder (TaxCalculator.Tax initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TaxCalculator.TaxHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TaxCalculator.TaxHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TaxCalculator.TaxHelper.type ();
  }

}
