package TaxCalculator;


/**
* TaxCalculator/Tax.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaxCalculator.idl
* Tuesday, March 25, 2014 11:18:21 AM EDT
*/

public interface Tax extends TaxOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tax
