package TaxCalculator;


/**
* TaxCalculator/TaxOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaxCalculator.idl
* Tuesday, March 25, 2014 11:18:21 AM EDT
*/

public interface TaxOperations 
{
  double getTax (double cost);
  String getClientID (int clientID);
  void shutdown ();
} // interface TaxOperations
