package Inter;


/**
* Inter/DBClientListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rinard.idl
* Tuesday, March 25, 2014 11:50:29 AM EDT
*/

public interface DBClientListenerOperations 
{
  void doWork ();
} // interface DBClientListenerOperations
