package Inter;


/**
* Inter/DBClientListenerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rinard.idl
* Tuesday, March 25, 2014 11:50:29 AM EDT
*/

public abstract class DBClientListenerPOA extends org.omg.PortableServer.Servant
 implements Inter.DBClientListenerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("doWork", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Inter/DBClientListener/doWork
       {
         this.doWork ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Inter/DBClientListener:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DBClientListener _this() 
  {
    return DBClientListenerHelper.narrow(
    super._this_object());
  }

  public DBClientListener _this(org.omg.CORBA.ORB orb) 
  {
    return DBClientListenerHelper.narrow(
    super._this_object(orb));
  }


} // class DBClientListenerPOA
