package Inter;


/**
* Inter/DBClientListenerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rinard.idl
* Tuesday, March 25, 2014 11:50:29 AM EDT
*/

abstract public class DBClientListenerHelper
{
  private static String  _id = "IDL:Inter/DBClientListener:1.0";

  public static void insert (org.omg.CORBA.Any a, Inter.DBClientListener that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Inter.DBClientListener extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Inter.DBClientListenerHelper.id (), "DBClientListener");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Inter.DBClientListener read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DBClientListenerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Inter.DBClientListener value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Inter.DBClientListener narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Inter.DBClientListener)
      return (Inter.DBClientListener)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Inter._DBClientListenerStub stub = new Inter._DBClientListenerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Inter.DBClientListener unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Inter.DBClientListener)
      return (Inter.DBClientListener)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Inter._DBClientListenerStub stub = new Inter._DBClientListenerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
