package Inter;


/**
* Inter/DBControlServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rinard.idl
* Tuesday, March 25, 2014 11:50:29 AM EDT
*/

public interface DBControlServer extends DBControlServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DBControlServer
