package Inter;

/**
* Inter/DBControlServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rinard.idl
* Tuesday, March 25, 2014 11:50:29 AM EDT
*/

public final class DBControlServerHolder implements org.omg.CORBA.portable.Streamable
{
  public Inter.DBControlServer value = null;

  public DBControlServerHolder ()
  {
  }

  public DBControlServerHolder (Inter.DBControlServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Inter.DBControlServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Inter.DBControlServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Inter.DBControlServerHelper.type ();
  }

}
