package Tracker;


/**
* Tracker/TimeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tracker.idl
* Tuesday, March 11, 2014 11:35:10 AM EDT
*/

abstract public class TimeHelper
{
  private static String  _id = "IDL:Tracker/Time:1.0";

  public static void insert (org.omg.CORBA.Any a, Tracker.Time that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Tracker.Time extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Tracker.TimeHelper.id (), "Time");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Tracker.Time read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TimeStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Tracker.Time value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Tracker.Time narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Tracker.Time)
      return (Tracker.Time)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Tracker._TimeStub stub = new Tracker._TimeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Tracker.Time unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Tracker.Time)
      return (Tracker.Time)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Tracker._TimeStub stub = new Tracker._TimeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
