package Tracker;

/**
* Tracker/TimeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tracker.idl
* Tuesday, March 11, 2014 11:35:10 AM EDT
*/

public final class TimeHolder implements org.omg.CORBA.portable.Streamable
{
  public Tracker.Time value = null;

  public TimeHolder ()
  {
  }

  public TimeHolder (Tracker.Time initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Tracker.TimeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Tracker.TimeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Tracker.TimeHelper.type ();
  }

}
