package Tracker;


/**
* Tracker/Time.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tracker.idl
* Tuesday, March 11, 2014 11:35:10 AM EDT
*/

public interface Time extends TimeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Time
